/// Flutter icons MoonX
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoonX
///      fonts:
///       - asset: fonts/MoonX.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MoonX {
  MoonX._();

  static const _kFontFam = 'MoonX';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData btn_tabbar_homeunselected =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData btn_tabbar_profileunselected =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData btn_tabbar_meditationunselected =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
